all: html

SPHINX_PROJECT_NAME = sliceKIT GPIO and Wi-Fi Combo Demo Quickstart Guide
VERSION = 0.1
SOURCE_INCLUDE_DIRS = ../app_sk_gpio_wifi_tiwisl_combo_demo
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
