all: html

SPHINX_PROJECT_NAME = GPIO Ethernet Combo Demo Quickstart Guide
VERSION = 0.1
SOURCE_INCLUDE_DIRS = ../app_sk_gpio_eth_combo_demo
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
