all: html

SPHINX_PROJECT_NAME = GPIO Application
VERSION = 0.1
DOXYGEN_DIRS = ../sw_gpio_examples
SOURCE_INCLUDE_DIRS = ../../app_slicekit_com_Demo
XDOC_DIR ?= ../../xdoc
include $(XDOC_DIR)/Makefile.inc
