all: html

SPHINX_PROJECT_NAME = GPIO Application
VERSION = 0.1
DOXYGEN_DIRS = ../app_slicekit_com_demo
SOURCE_INCLUDE_DIRS = ../app_slicekit_com_demo
XDOC_DIR ?= ../../xdoc
include $(XDOC_DIR)/Makefile.inc
