all: html

SPHINX_PROJECT_NAME = GPIO Application
VERSION = 0.1
DOXYGEN_DIRS = ../app_sk_gpio_com_demo ../app_sk_gpio_simple_demo
SOURCE_INCLUDE_DIRS = ../app_sk_gpio_simple_demo ../app_sk_gpio_com_demo
XDOC_DIR ?= ../../xdoc
include $(XDOC_DIR)/Makefile.inc
